package com.windroid.xp

import android.content.Context
import android.content.Intent
import android.provider.Settings
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Composable internal fun RunWindow(apps: List<LaunchableApp>, context: Context, onLaunch: (LaunchableApp) -> Unit, onClose: () -> Unit, modifier: Modifier = Modifier) { var query by remember { mutableStateOf("") }; val matches = remember(query, apps) { if (query.isBlank()) emptyList() else apps.filter { it.label.contains(query, true) || it.packageName.contains(query, true) }.take(6) }; XPWindow("Run", modifier, onClose = onClose) { Text("Type the name of a program, package, or command.", fontSize = 11.sp); Spacer(Modifier.height(8.dp)); BasicTextField(value = query, onValueChange = { query = it.take(80) }, singleLine = true, modifier = Modifier.fillMaxWidth().background(Color.White).border(1.dp, Color(0xFF7F9DB9)).padding(7.dp)); if (matches.isNotEmpty()) { Spacer(Modifier.height(7.dp)); matches.forEach { app -> Row(Modifier.fillMaxWidth().clickable { onLaunch(app) }.padding(vertical = 5.dp), verticalAlignment = Alignment.CenterVertically) { if (app.icon != null) Image(bitmap = app.icon, contentDescription = null, modifier = Modifier.size(24.dp)); Spacer(Modifier.width(7.dp)); Text(app.label, fontSize = 12.sp, maxLines = 1, overflow = TextOverflow.Ellipsis) } } }; Spacer(Modifier.height(9.dp)); Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { XPActionButton("OK") { when (query.trim().lowercase()) { "settings", "control" -> context.startActivity(Intent(Settings.ACTION_SETTINGS)); "files", "documents", "explorer" -> openDocuments(context); "browser", "internet", "iexplore" -> openDefaultBrowser(context); else -> matches.firstOrNull()?.let(onLaunch) } }; XPActionButton("Cancel") { onClose() } } } }
@Composable internal fun ProfileWindow(currentName: String, currentAvatar: String, onSave: (String, String) -> Unit, onCancel: () -> Unit, modifier: Modifier = Modifier) { var draftName by remember(currentName) { mutableStateOf(currentName) }; var draftAvatar by remember(currentAvatar) { mutableStateOf(currentAvatar) }; val avatars = listOf("🙂", "😎", "🤖", "🐺", "🦊", "🐱", "👾", "🧑"); XPWindow("User Accounts", modifier, onClose = onCancel) { Text("Pick a name and picture for your account.", fontSize = 13.sp); Spacer(Modifier.height(12.dp)); Text("User name", fontSize = 11.sp, fontWeight = FontWeight.Bold); Spacer(Modifier.height(4.dp)); BasicTextField(value = draftName, onValueChange = { if (it.length <= 24) draftName = it }, singleLine = true, modifier = Modifier.fillMaxWidth().background(Color.White).border(1.dp, Color(0xFF7F9DB9)).padding(7.dp)); Spacer(Modifier.height(12.dp)); Text("Account picture", fontSize = 11.sp, fontWeight = FontWeight.Bold); Spacer(Modifier.height(7.dp)); Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState())) { avatars.forEach { avatar -> Box(Modifier.padding(end = 7.dp).size(42.dp).background(Color.White, RoundedCornerShape(4.dp)).border(if (avatar == draftAvatar) 2.dp else 1.dp, if (avatar == draftAvatar) Color(0xFF245EDB) else Color(0xFFB7B7B7), RoundedCornerShape(4.dp)).clickable { draftAvatar = avatar }, contentAlignment = Alignment.Center) { Text(avatar, fontSize = 25.sp) } } }; Spacer(Modifier.height(16.dp)); Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { XPActionButton("Save") { onSave(draftName, draftAvatar) }; XPActionButton("Cancel") { onCancel() } } } }

@Composable internal fun FamilySetupWizard(context: Context, userName: String, onNameChanged: (String) -> Unit, onFinish: () -> Unit, modifier: Modifier = Modifier) { var page by remember { mutableIntStateOf(0) }; XPWindow("Welcome to Windroid XP", modifier.width(350.dp), onClose = null) { when (page) { 0 -> { Text("Welcome to Windroid XP", fontWeight = FontWeight.Bold, fontSize = 18.sp, color = Color(0xFF003399)); Spacer(Modifier.height(8.dp)); Text("This replaces your Home screen with a Windows XP-style launcher. Your Android apps, photos, messages, and settings stay on the phone.", fontSize = 11.sp); Spacer(Modifier.height(12.dp)); XPActionButton("Next") { page = 1 } }; 1 -> { Text("Choose your account name", fontWeight = FontWeight.Bold, fontSize = 14.sp); Spacer(Modifier.height(8.dp)); BasicTextField(value = userName, onValueChange = { onNameChanged(it.take(24)) }, singleLine = true, modifier = Modifier.fillMaxWidth().background(Color.White).border(1.dp, Color(0xFF7F9DB9)).padding(8.dp)); Spacer(Modifier.height(12.dp)); Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { XPActionButton("Back") { page = 0 }; XPActionButton("Next") { page = 2 } } }; else -> { Text("Make Windroid XP your Home app", fontWeight = FontWeight.Bold, fontSize = 14.sp); Spacer(Modifier.height(8.dp)); Text("Android will show the Home-app chooser. Select Windroid XP if it is not already selected. You can always get back there from Start → Turn Off Computer.", fontSize = 11.sp); Spacer(Modifier.height(10.dp)); XPActionButton("Open Home App Settings") { try { context.startActivity(Intent(Settings.ACTION_HOME_SETTINGS)) } catch (_: Exception) { context.startActivity(Intent(Settings.ACTION_SETTINGS)) } }; Spacer(Modifier.height(10.dp)); Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { XPActionButton("Back") { page = 1 }; XPActionButton("Finish") { onFinish() } } } } } }
